server:
  port: ${APPLICATION_SERVER_PORT}
  tomcat:
    threads:
      max: 10

spring:
  application:
    name: application-service

logging:
  level:
    root: INFO
    org.mongodb.driver: WARN
    org.springframework.data.mongodb: WARN

application:
  mongodb:
    uri: ${APPLICATION_MONGO_URI}
    database: ${APPLICATION_MONGO_DATABASE}

candidate:
  grpc:
    host: localhost
    port: 9091