server:
  port: ${CANDIDATE_SERVER_PORT}
  tomcat:
    threads:
      max: 10

spring:
  application:
    name: candidate-service

logging:
  level:
    root: INFO
    org.mongodb.driver: WARN
    org.springframework.data.mongodb: WARN

candidate:
  mongodb:
    uri: ${CANDIDATE_MONGO_URI}
    database: ${CANDIDATE_MONGO_DATABASE}

minio:
  endpoint: ${MINIO_ENDPOINT}
  access-key: ${MINIO_ACCESS_KEY}
  secret-key: ${MINIO_SECRET_KEY}
  bucket: ${MINIO_BUCKET}

gprc:
  server:
    port: ${GRPC_SERVER_PORT}