server:
  port: ${JOB_SERVER_PORT}
  tomcat:
    threads:
      max: 10

spring:
  application:
    name: job-service

logging:
  level:
    root: INFO
    org.mongodb.driver: WARN
    org.springframework.data.mongodb: WARN

job:
  mongodb:
    uri: ${JOB_MONGO_URI}
    database: ${JOB_MONGO_DATABASE}
