services:
  mongodb:
    image: mongo:7.0
    container_name: candidate-mongodb
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: candidate_db
    volumes:
      - ./data/mongodb_data:/data/db

volumes:
  mongodb_data: