services:
  minio:
    image: minio/minio:latest
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123456
    volumes:
      - minio_data:/data
    command: server /data --console-address ":9001"

  nats:
    image: nats:latest
    container_name: nats
    ports:
      - "4222:4222"
      - "8222:8222"
    command:
      - "-js"
      - "-sd"
      - "/data"
      - "-m"
      - "8222"
    volumes:
      - nats_data:/data

volumes:
  minio_data:
  nats_data: